name: Print Hello

# This triggers the workflow on a push to the main branch 
# or manually from the Actions tab (workflow_dispatch).
on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  print-greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "hello prashant"